### ISSUE TITLE
Additional entries

### ISSUE THREAD

**Issue by EricDarve** [gchavez2/awesome-hierarchical-matrices#3]
A couple of additional entries:

LORASPX
https://bitbucket.org/hadip/loraspx
A revised version of LORASP with additional options and a more modular software design

BBFMM3D
https://github.com/ruoxi-wang/BBFMM3D
Black-box fast multipole method for general kernels. The FMM is based on Chebyshev and Fourier interpolation methods.

**Comment by gchavez2** [comment]
Updated, thanks!
